### ISSUE TITLE
Рефакторинг всего кода!

### ISSUE THREAD

**Issue by temikfart** [temikfart/pdp11-emulator#16]
Нужно принять code style и сделать рефакторинг.

**Comment by temikfart** [comment]
Сделан полный рефакторинг кода.

- Для каждого .c файла есть свой .h файл.
- Есть необходимые включения заголовочных файлов.
- Уменьшено количество глобальных переменных.
- Принят code style: https://google.github.io/styleguide/cppguide.html#Include_What_You_Use [Google C++ Style Guide]

**Comment by hankou-code** [comment]
Решено в 25751f0
